### ISSUE TITLE
conflict with org-capture

### ISSUE THREAD

**Issue by lrcg** [polymode/polymode#40]
I'm sorry I don't have time to look into the details further, but it seems that polymode prevents org-capture from working correctly. After entering the indirect buffer, the normal `C-c C-c` to complete the capture doesn't work. Disabling polymode for `.org` files resolves this issue.

**Comment by vspinu** [comment]
This one seem to have been fixed. Org has never been functional with polymode but after a recent rewrite it seems to be working just fine. At least that's the case for my quick tests.

**Comment by vspinu** [comment]
It's actually still there but under different form :(. Will look into it asap.

**Comment by SteveLane** [comment]
This is still occurring. Can you point to any location where you think the bug may be creeping in? I'm not sure that my lisp skills are up to scratch, but if you can nail it down somewhat I could possibly take a look.

**Comment by noctuid** [comment]
> It's actually still there but under different form :(. Will look into it asap.

Is this still an issue? Finalizing the capture works fine for me, and I have not noticed any problems. Maybe this can be closed.

**Comment by vspinu** [comment]
Indeed. Works for me too.

**Comment by jdtonkin** [comment]
I had this problem too and deleting org-poly removed the issue.

**Comment by vspinu** [comment]
This is a very old issue. Have you seen the issue after the rewrite (say past 2 weeks)?
